config/routes.rb
Rails.application.routes.draw do

  resources :users

  root :to => 'application#home', :as => :home


end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user

  has_attached_file :photo, :styles => { :small => "200x200>" },
                    :url  => "/assets/users/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/users/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/models/social.rb
class Social < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :socials
  has_many :photos

  accepts_nested_attributes_for :socials,:reject_if => lambda {|a|a[:name].blank?}, allow_destroy: true
  accepts_nested_attributes_for :photos,:reject_if => lambda {|a|a[:photo].blank?}, allow_destroy: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  layout 'admin_lte_2' #set layout from gem adminlte
  def home
    render "static_page/home"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      if params[:rut] != ''
        format.json {
          render( :json => @users = User.all.where("rut LIKE ?", "%#{params[:term]}%").map(&:rut))
        }
      end
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json {render :json =>@user}
      end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        format.js
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:rut, :name,:lastname, :email, :birth_date, :password,
                                   socials_attributes:[:id, :name, :social_type,:_destroy],
                                   photos_attributes:[:id, :photo,:_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>Test</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Test</b></span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">

      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
        <!-- Optionally, you can add icons to the links -->
      <li>
        <%= link_to home_path  do %>
            <i class='fa fa-home'></i> <span>Home</span>
        <% end %>
      </li>
      <li>
        <%= link_to users_path  do %>
            <i class='fa fa-users'></i> <span>Users</span>
        <% end %>
      </li>
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin_lte_2.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Test</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>

<body class="skin-purple sidebar-mini sidebar-collapse <%= params[:controller].parameterize %> <%= action_name %>">
  <div class="wrapper">

    <%= render partial: 'layouts/admin_lte_2_header' %>

    <%= render partial: 'layouts/admin_lte_2_sidebar' %>

    <div class="content-wrapper">
      <!-- Main content -->
      <%= yield %>
    </div><!-- /.content-wrapper -->

  </div><!-- ./wrapper -->

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_page/home.erb
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
      Autocomplete Demo
    <small>using jquery-ui</small>

  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="#">Autocomplete</a></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-6">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Quick Example</h3>
        </div><!-- /.box-header -->
        <!-- form start -->
        <form role="form">
          <div class="box-body">
            <div class="form-group">
              <label>Rut</label>
              <%= text_field_tag( 'rut', nil, :id => 'rut', data: {autocomplete_source: users_path } )%>
              <p>Autocompletar con datos via json usando jquery. Falto realizar que se actualicen los demás campos</p>
            </div>

            <div class="form-group">
              <label>Lastname</label>
              <input type="text" class="form-control" id="lastname" placeholder="Enter a Lastname">
            </div>

            <div class="form-group">
              <label >email</label>
              <input type="text" class="form-control" id="email" placeholder="Enter an Email">
            </div>
          </div><!-- /.box-body -->

          <div class="box-footer">

          </div>
        </form>
      </div><!-- /.box -->
    </div><!--/.col (right) -->
  </div>   <!-- /.row -->
</section><!-- /.content -->
</div><!-- /.content-wrapper -->

app/views/users/_form.html.erb
<%= form_for  @user, :html => { :multipart => true }, :remote => true do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="box-body">
      <div class="form-group">
        <%= f.label :rut %><br>
        <%= f.text_field :rut  , :class => 'form-control'%>
      </div>

      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name  , :class => 'form-control'%>
      </div>

      <div class="form-group">
        <%= f.label :lastname %><br>
        <%= f.text_field :lastname  , :class => 'form-control'%>
      </div>

      <div class="form-group">
        <%= f.label :email %><br>
        <%= f.text_field :email  , :class => 'form-control'%>
      </div>

      <div class="field">
        <%= f.label :birth_date %><br>
        <%= f.date_select :birth_date %>
      </div>

      <div class="form-group">
        <%= f.label :password %><br>
        <%= f.password_field :password  , :class => 'form-control'%>
      </div>

    </div>

    <div class="form-group">
      <div class="box box-info">
        <div class="box-header">
          <h3 class="box-title">Social Networks</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <%= f.fields_for :socials do |social| %>
              <%= render 'social', :f => social %>
          <% end %>
          <p><%= link_to_add_association "Add Social",f, :socials, :class=> "btn btn-primary pull-right", :partial => "social" %></p>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="box box-info">
        <div class="box-header">
          <h3 class="box-title">Profile Image</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <%= f.fields_for :photos do |photo| %>
              <%= render 'photo', :f => photo %>
          <% end %>
          <p><%= link_to_add_association "Add Profile Picture",f, :photos, :class=> "btn btn-primary pull-right", :partial => "photo" %></p>
        </div>
      </div>
    </div>

    </div><!-- /.box-body -->
    <div class="box-footer">
      <%= f.submit "Save", :class => "btn btn-primary" %>
      <%= link_to 'Back', users_path ,:class =>"btn bg-purple margin"%>
      <p>Falta la redireccion de la pagina al momento de hacer el submit de las fotos. al presionar back ya estaran cargadas</p>
    </div>
<% end %>

app/views/users/_photo.html.erb
<div class="nested-fields">
  <div class="input-group">
    <div class="row">
      <div class="col-sm-4">
        <%= f.label :photo, "Photo", class: "col-sm-2 control-label" %>
        <%= f.file_field :photo, class: "form-control"%>
      </div>
    </div>
    <div class="input-group-btn">
      <%= link_to_remove_association "Remove",f , :class =>"btn btn-danger" %>
    </div><!-- /btn-group -->
  </div>
</div>

app/views/users/_social.html.erb
<div class="nested-fields">
  <div class="input-group">
    <div class="row">
      <div class="col-sm-4">
        Name :
        <%= f.text_field :name, :class => 'form-control'%>
      </div>
      <div class="col-sm-4">
        Social Type :
        <%= f.text_field :social_type, :class => 'form-control'%>
      </div>
    </div>
    <div class="input-group-btn">
      <%= link_to_remove_association "Remove",f , :class => "btn btn-danger" %>
    </div><!-- /btn-group -->
  </div>
</div>

app/views/users/create.js.erb
// Display a Javascript alert
alert('success!');
<% if remotipart_submitted? %>
alert('submitted via remotipart')
<% else %>
alert('submitted via native jquery-ujs')
<% end %>

app/views/users/edit.html.erb
<section class="content-header">
  <h1>
    Users
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="#">Users</a></li>
    <li class="active">Edit User</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Edit User</h3>
        </div><!-- /.box-header -->
        <!-- form start -->
        <%= render 'form' %>
      </div><!-- /.box -->
    </div>
  </div>   <!-- /.row -->
</section><!-- /.content -->

app/views/users/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Users

  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Users Admin</li>
    <li class="active">Users</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Users List</h3>
          <div class="box-tools">
            <%= link_to 'New User' ,new_user_path,:class =>"btn btn-primary btn-xs"%>
          </div>
        </div><!-- /.box-header -->
        <div class="box-body table-responsive" style="overflow-x: inherit">
          <table id="users" class="datatable table table-condensed table-bordered table-hover responsive no-wrap">
            <thead>
            <tr>
              <th>Email</th>
              <th>Name</th>
              <th>Lastname</th>
              <th>Rut</th>
              <th>Profile Image</th>
              <th>Actions</th>
            </tr>
            </thead>

            <tbody>
            <%@users.each do |user|%>
                <tr>
                  <td><%= user.email %></td>
                  <td><%= user.name %></td>
                  <td><%= user.lastname %></td>
                  <td><%= user.rut %></td>
                  <%if user.photos.count > 0%>
                      <td><%= image_tag user.photos.first.photo.url(:small) %></td>
                  <% else %>
                      <td></td>
                  <%end%>

                  <td>
                    <%= link_to 'Show', user , :class =>"btn btn-primary btn-block btn-xs"%>
                    <%= link_to 'Edit', edit_user_path(user),:class =>"btn btn-warning btn-block btn-xs" %>
                    <%= link_to 'Delete', user, method: :delete, data: { confirm: 'are you sure?' },:class =>"btn btn-danger btn-block btn-xs"%>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div><!-- /.col -->
  </div><!-- /.row -->
</section><!-- /.content -->

app/views/users/new.html.erb
<section class="content-header">
  <h1>
    Users
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="#">Users Admin</a></li>
    <li><a href="#">Users</a></li>
    <li class="active">New User</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">New User</h3>
        </div><!-- /.box-header -->
        <!-- form start -->
        <%= render 'form' %>

      </div><!-- /.box -->
    </div>
  </div>   <!-- /.row -->
</section><!-- /.content -->

app/views/users/show.html.erb
<section class="content-header">
  <h1>
    Users
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="#">Users Admin</a></li>
    <li><a href="#">Users</a></li>
    <li class="active">User Details</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-12">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">User Details</h3>
        </div><!-- /.box-header -->
        <!-- form start -->
        <div class="box-body">
          <p>
            <strong>Email:</strong>
            <%= @user.email %>
          </p>
          <p>
            <strong>Name:</strong>
            <%= @user.name %>
          </p>
          <p>
            <strong>Lastname:</strong>
            <%= @user.lastname %>
          </p>
          <p>
            <strong>Rut</strong>
            <%= @user.rut %>
          </p>
          <p>
            <strong>Birthdate:</strong>
            <%= @user.birth_date %>
          </p>
          <div class="row">
            <div class="col-md-10">
              <div class="box box-default">
                <div class="box-header with-border">
                  <i class="fa fa-facebook-official"></i>
                  <h3 class="box-title">Social Networks</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <% @user.socials.each do |item| %>
                        <dt>Social Type:<%=item.social_type%></dt>
                        <dd>Name:<%=item.name %></dd>
                  <% end %>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div> <!-- /.row -->

          <div class="row">
            <div class="col-md-10">
              <div class="box box-default">
                <div class="box-header with-border">
                  <i class="fa fa-file-image-o"></i>
                  <h3 class="box-title">Profile pictures</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <% @user.photos.each do |item| %>
                      <%= image_tag item.photo.url(:small) %>
                <% end %>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div> <!-- /.row -->
        </div>

        <div class="box-footer">
          <%= link_to 'Edit', edit_user_path(@user),:class =>"btn bg-purple margin"%>
          <%= link_to 'Back', users_path,:class =>"btn bg-purple margin"%>
        </div>
      </div><!-- /.box -->
    </div>
  </div>   <!-- /.row -->
</section><!-- /.content -->

app/views/users/update.js.erb
// Display a Javascript alert
alert('success!');
<% if remotipart_submitted? %>
alert('submitted via remotipart')
alert('presionar Back para volver al index')
<% else %>
alert('submitted via native jquery-ujs')
alert('presionar Back para volver al index')
<% end %>